### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by rubensa** [wso2/ei-tooling-vscode#45]
**Description:**

On June 5, 2019 @sajinieKavindya told us [on medium](https://medium.com/think-integration/getting-started-with-vs-code-extension-for-wso2-ei-986abac97e8f) that:

> For the moment, the extension supports only the source view for integration development. But soon the plugin will be featured by the graphical view, providing you with flawless and much more enhanced development experience.

More than 2 years have passed and it seems that the project has made absolutely no progress so I'm thinking if it is still alive and there is any interest in the SWO2 community in keeping developing it.

**Suggested Labels:**

development, documentation

**Suggested Assignees:**

@sajinieKavindya

**Affected Product Version:**
v0.7.5 (current)

**OS, DB, other environment details and versions:**    
Any.

**Steps to reproduce:**
Not needed.

**Related Issues:**
#37

**Comment by sajinieKavindya** [comment]
@rubensa This project is not in active development at the moment since our team is focused on the WSO2 Integration Studio (https://wso2.com/integration/integration-studio/) development, which is the alternative to this plugin. But we are still planning to deliver the new updates to this project. I have no exact ETA but this is all information that I can provide.

**Comment by rubensa** [comment]
Thanks for the answer @sajinieKavindya

**Comment by narus2** [comment]
Good day. 
The latest update (14.09.2022 v:0.8.0) doesn't work at all. I have to roll back. Are there any plans to finish it? Also, the Eclipse-based IDE is very inconvenient when you have a large project.

**Comment by GDLMadushanka** [comment]
This plugin is no longer maintained. 
Please find the new plugin in https://marketplace.visualstudio.com/items?itemName=WSO2.micro-integrator
