### ISSUE TITLE
Cannot install the extension

### ISSUE THREAD

**Issue by JoneSabino** [wso2/ei-tooling-vscode#9]
**Description:**
Error messages:
Trying from the IDE extensions Marketplace:
"Failed to install 'wso2.wso2ei'."

Trying from the web MarketPlace:
"Cannot read property 'identifier' of null"

**Affected Product Version:**
0.5.4
**OS, DB, other environment details and versions:**    
MacOS Mojave 10.14.5
Maven 3.6.0
Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home

**Comment by sajinieKavindya** [comment]
@JoneSabino If you are still getting the same error, could you please specify your VS Code version  to reproduce the issue?
